
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="column h-screen">
      <Header/>
      <SideBar/>
      {children}
    </div>
  )
}
